//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_hoax
    {
        public string Hoax_Name { get; set; }
        public string Hoax_City { get; set; }
        public string Hoax_Email { get; set; }
        public string hoax_Contactno { get; set; }
        public string Hoax_Postcode { get; set; }
    }
}
